name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java_version: [11, 17, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Support longpaths
      run: git config core.longpaths true
    - name: Download submodules
      run: git submodule update --init --recursive
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java_version }}
        distribution: temurin
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.3
      if: matrix.os == 'windows-latest'
      with:
        minimum-size: 6GB
    - name: Build plugin
      uses: gradle/gradle-build-action@v2.11.1
      with:
        arguments: check --scan
        build-root-directory: plugin
    - name: Build base
      uses: gradle/gradle-build-action@v2.11.1
      with:
        arguments: check --scan
        build-root-directory: ""
    - name: Upload coverage reports to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.java_version == '11'
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
